PipelineSecrets: {}
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: ip-example.com
    exposer: Ingress
    http: "true"
jenkins:
  Servers:
    Global:
      EnvVars:
        DOCKER_REGISTRY: 511012381298.dkr.ecr.eu-west-1.amazonaws.com
        TILLER_NAMESPACE: tiller
prow: {}
